.bail on
.timeout 10000

PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

CREATE TEMP TABLE tag_localization_map (
    source TEXT PRIMARY KEY,
    target TEXT NOT NULL,
    expected_count INTEGER NOT NULL
);

INSERT INTO tag_localization_map(source, target, expected_count) VALUES
    ('3d', '3D', 4),
    ('3d-design', '3D 设计', 2),
    ('3d-editor', '3D 编辑器', 1),
    ('3d-icons', '3D 图标', 1),
    ('3d-illustrations', '3D 插画', 1),
    ('3d-mockup', '3D 样机', 1),
    ('3d-model', '3D 模型', 2),
    ('abstraction', '抽象', 2),
    ('access-control', '访问控制', 1),
    ('accessibility', '无障碍访问', 10),
    ('accessible', '无障碍', 1),
    ('account', '账户', 1),
    ('activation-codes', '激活码', 1),
    ('ad-blocker', '广告拦截', 1),
    ('address-generator', '地址生成器', 1),
    ('address-tracker', '地址追踪器', 1),
    ('address-validation', '地址校验', 1),
    ('admin', '管理后台', 4),
    ('admin-panel', '管理后台', 5),
    ('admin-template', '后台模板', 6),
    ('advanced', '进阶', 2),
    ('aesthetics', '美学', 1),
    ('agent-framework', 'agent 框架', 1),
    ('agent-management', 'agent 管理', 2),
    ('agent-memory', 'agent 记忆', 7),
    ('aggregate', '聚合', 1),
    ('aggregate-design', '聚合设计', 1),
    ('aggregation', '聚合', 2),
    ('aggregator', '聚合器', 2),
    ('ai', 'AI', 71),
    ('ai-agent', 'AI-agent', 11),
    ('ai-art', 'AI 艺术', 3),
    ('ai-assistant', 'AI 助手', 2),
    ('ai-chat', 'AI 聊天', 6),
    ('ai-client', 'AI 客户端', 1),
    ('ai-code-review', 'AI 代码评审', 1),
    ('ai-coding', 'AI 编程', 1),
    ('ai-coding-agent', 'AI 编程 agent', 2),
    ('ai-gateway', 'AI 网关', 1),
    ('ai-logo-generator', 'AI Logo 生成器', 1),
    ('ai-native', 'AI 原生', 1),
    ('ai-news', 'AI 资讯', 1),
    ('ai-pair-programming', 'AI 结对编程', 1),
    ('ai-prompts', 'AI 提示词', 1),
    ('ai-search', 'AI 搜索', 1),
    ('ai-search-engine', 'AI 搜索引擎', 1),
    ('ai-service', 'AI 服务', 1),
    ('ai-summarizer', 'AI 摘要工具', 1),
    ('ai-tools', 'AI 工具', 3),
    ('airdrop', '空投', 6),
    ('algorithm', '算法', 16),
    ('alias', '别名', 2),
    ('alternatives', '替代方案', 2),
    ('analytics', '分析', 12),
    ('annotation', '注解', 2),
    ('anonymous-chat', '匿名聊天', 1),
    ('anonymous-email', '匿名邮件', 1),
    ('answer-engine', '问答引擎', 2),
    ('app-icon', '应用 icon', 2),
    ('appearance', '外观', 1),
    ('arbitrary-precision', '任意精度', 2),
    ('architectural-design', '架构设计', 1),
    ('architecture', '架构', 5),
    ('archive', '归档', 1),
    ('archiving', '归档', 2),
    ('arithmetic', '算术', 1),
    ('array', '数组', 2),
    ('art', '艺术', 1),
    ('asset-management', '素材管理', 1),
    ('assets', '素材', 4),
    ('asynchronous', '异步', 1),
    ('audio', '音频', 7),
    ('audio-fingerprint', '音频指纹', 1),
    ('authorization', '授权', 1),
    ('auto-resize', '自动 resize', 1),
    ('autonomous-agent', '自主 agent', 1),
    ('awesome-list', '精选列表', 20),
    ('background-images', '背景图像', 2),
    ('backgrounds', '背景', 5),
    ('badge-generator', '徽章生成器', 1),
    ('beginner', '入门', 10),
    ('beginner-guide', '入门指南', 1),
    ('best-practices', '最佳实践', 10),
    ('big-number', '大数字', 2),
    ('binary', '二进制', 1),
    ('binary-search', '二进制搜索', 1),
    ('black-box-testing', '黑盒测试', 1),
    ('block-explorer', '区块浏览器', 10),
    ('boilerplate', '样板代码', 2),
    ('book-list', '书籍列表', 1),
    ('bookmark', '书签', 3),
    ('borrowing', '借贷', 2),
    ('bot-detection', '机器人检测', 1),
    ('bounded-context', '限界上下文', 1),
    ('brainstorming', '头脑风暴', 2),
    ('branching', '分支', 1),
    ('brand-design', '品牌设计', 2),
    ('brand-guidelines', '品牌规范', 1),
    ('brand-icons', '品牌 icons', 1),
    ('branding', '品牌设计', 1),
    ('bridge', '跨链桥', 8),
    ('bridge-protocol', '跨链桥协议', 1),
    ('browser-architecture', '浏览器架构', 1),
    ('browser-automation', '浏览器自动化', 3),
    ('browser-compatibility', '浏览器兼容性', 11),
    ('browser-detection', '浏览器检测', 2),
    ('browser-engine', '浏览器引擎', 1),
    ('browser-fingerprint', '浏览器指纹', 2),
    ('browser-game', '浏览器游戏', 1),
    ('browser-mock', '浏览器 mock', 1),
    ('browser-upgrade', '浏览器升级', 1),
    ('bug-tracking', 'bug 追踪', 1),
    ('build-tool', '构建工具', 8),
    ('bundle-analysis', '包体分析', 1),
    ('bundler', '打包器', 8),
    ('bundling', '打包', 15),
    ('button', '按钮', 5),
    ('buying-guide', '购买指南', 1),
    ('caching', '缓存', 5),
    ('calculation-engine', '计算引擎', 1),
    ('calendar', '日历', 3),
    ('callback', '回调', 1),
    ('canary-release', '金丝雀发布', 1),
    ('card', '卡片', 2),
    ('career', '职业', 2),
    ('career-guide', '职业指南', 1),
    ('case-study', '案例研究', 3),
    ('certificate', '证书', 1),
    ('challenge', '挑战', 2),
    ('change-detection', '变更检测', 6),
    ('changelog', '更新日志', 2),
    ('character-ai', '字符 AI', 1),
    ('character-conversion', '字符转换', 1),
    ('chart-library', '图表代码库', 1),
    ('charting-library', '图表代码库', 1),
    ('chat', '聊天', 3),
    ('chatbot', '聊天机器人', 6),
    ('checker', '检查器', 2),
    ('checklist', '检查清单', 2),
    ('china', '中国', 11),
    ('chinese', '中文', 86),
    ('chinese-book', '中文书籍', 1),
    ('chinese-documentation', '中文文档', 2),
    ('chinese-font', '中文字体', 1),
    ('chinese-number', '中文数字', 2),
    ('chinese-translation', '中文翻译', 3),
    ('chinese-website', '中文网站', 1),
    ('class', '类', 1),
    ('class-diagram', '类图表', 2),
    ('client', '客户端', 2),
    ('client-server', '客户端服务器', 1),
    ('clipboard', '剪贴板', 2),
    ('cloud', '云', 9),
    ('cloud-hosting', '云托管', 2),
    ('cloud-server', '云服务器', 1),
    ('cloud-sync', '云同步', 1),
    ('cloud-testing', '云测试', 1),
    ('code-analysis', '代码分析', 2),
    ('code-assistant', '代码助手', 1),
    ('code-coverage', '代码覆盖率', 1),
    ('code-diff', '代码 diff', 2),
    ('code-documentation', '代码文档', 2),
    ('code-editing', '代码编辑', 1),
    ('code-formatter', '代码格式化工具', 1),
    ('code-formatting', '代码格式化', 1),
    ('code-generator', '代码生成器', 1),
    ('code-highlight', '代码高亮', 1),
    ('code-hosting', '代码托管', 1),
    ('code-navigation', '代码导航', 1),
    ('code-organization', '代码组织', 1),
    ('code-patch', '代码补丁', 1),
    ('code-quality', '代码质量', 9),
    ('code-review', '代码审查', 5),
    ('code-screenshot', '代码截图', 1),
    ('code-search', '代码搜索', 1),
    ('code-sharing', '代码分享', 1),
    ('coding-agent', '编程 agent', 5),
    ('coding-exercises', '编程练习', 1),
    ('coding-style', '编程样式', 1),
    ('collaboration', '协作', 16),
    ('collapsible', '可折叠', 1),
    ('collision-detection', '碰撞检测', 1),
    ('color-conversion', '颜色转换', 2),
    ('color-converter', '颜色转换器', 2),
    ('color-gradient', '颜色渐变', 2),
    ('color-inspiration', '颜色灵感', 1),
    ('color-picker', '颜色选择器', 3),
    ('commit-formatting', '提交格式化', 1),
    ('commit-linting', '提交代码检查', 1),
    ('community', '社区', 13),
    ('comparison', '对比', 16),
    ('compatibility', '兼容性', 2),
    ('compiler', '编译器', 8),
    ('component-bundling', '组件打包', 1),
    ('component-discovery', '组件发现', 1),
    ('component-documentation', '组件文档', 1),
    ('component-framework', '组件框架', 1),
    ('compression', '压缩', 3),
    ('computer-science', '计算机科学', 4),
    ('concept', '概念', 2),
    ('concurrency', '并发', 5),
    ('conference', '会议', 1),
    ('configuration-generator', '配置生成器', 1),
    ('configuration-management', '配置管理', 1),
    ('conflict-resolution', '冲突分辨率', 2),
    ('connectivity', '连接', 1),
    ('console', '控制台', 2),
    ('container-engine', '容器引擎', 1),
    ('containerization', '容器化', 2),
    ('content-addressing', '内容寻址', 1),
    ('content-aggregator', '内容聚合器', 1),
    ('content-editing', '内容编辑', 1),
    ('context-engineering', '上下文工程', 1),
    ('context-optimization', '上下文优化', 1),
    ('continuous-deployment', '持续部署', 1),
    ('continuous-integration', '持续集成', 2),
    ('controls', '控件', 1),
    ('convention', '约定', 1),
    ('conversion', '转换', 8),
    ('converter', '转换器', 2),
    ('coroutine', '协程', 2),
    ('cost-analysis', '成本分析', 1),
    ('crawler', '爬虫', 1),
    ('creative', '创意', 1),
    ('critique', '评审', 1),
    ('cross-browser-testing', '跨浏览器测试', 1),
    ('cross-framework', '跨框架', 4),
    ('cross-window', '跨窗口', 1),
    ('curated-list', '精选列表', 3),
    ('curation', '整理', 8),
    ('currency-formatting', '货币格式化', 3),
    ('custom-filter', '自定义筛选器', 2),
    ('custom-hook', '自定义 hook', 2),
    ('customization', '定制', 4),
    ('daily', '每日', 2),
    ('dark-theme', '深色 theme', 1),
    ('dashboard', '仪表盘', 12),
    ('data', '数据', 2),
    ('data-cleaning', '数据清理', 1),
    ('data-fetching', '数据获取', 3),
    ('data-generator', '数据生成器', 2),
    ('data-grid', '数据表格', 13),
    ('data-interaction', '数据交互', 1),
    ('data-migration', '数据迁移', 1),
    ('data-modeling', '数据建模', 1),
    ('data-processing', '数据处理', 5),
    ('data-validation', '数据校验', 1),
    ('data-visualization', '数据可视化', 15),
    ('database', '数据库', 17),
    ('database-design', '数据库设计', 2),
    ('database-sync', '数据库同步', 1),
    ('dataset', '数据集', 1),
    ('date', '日期', 5),
    ('debugging', '调试', 16),
    ('decentralized-exchange', '去中心化交易所', 2),
    ('decentralized-storage', '去中心化存储', 5),
    ('decentralized-web', '去中心化 Web', 1),
    ('decoder', '解码器', 2),
    ('decoding', '解码', 2),
    ('decorator', '装饰器', 3),
    ('decoupling', '解耦', 1),
    ('decryption', '解密', 2),
    ('deep-diff', '深度 diff', 1),
    ('deep-learning', '深度学习', 2),
    ('defensive-security', '防御安全', 1),
    ('dependency-graph', '依赖图', 2),
    ('dependency-injection', '依赖注入', 5),
    ('dependency-management', '依赖管理', 1),
    ('deployment', '部署', 15),
    ('deprecated', '已弃用', 1),
    ('design-analysis', '设计分析', 1),
    ('design-asset', '设计素材', 1),
    ('design-engineering', '设计工程', 1),
    ('design-inspiration', '设计灵感', 1),
    ('design-patterns', '设计模式', 3),
    ('design-resource', '设计资源', 4),
    ('design-system', '设计系统', 7),
    ('design-tool', '设计工具', 6),
    ('designer', '设计师', 1),
    ('desktop', '桌面端', 14),
    ('desktop-app', '桌面端应用', 2),
    ('detection', '检测', 5),
    ('developer', '开发者', 2),
    ('developer-news', '开发者资讯', 2),
    ('developer-tools', '开发者工具', 9),
    ('development', '开发', 3),
    ('development-environment', '开发环境', 3),
    ('development-server', '开发服务器', 1),
    ('diagnostics', '诊断', 2),
    ('diagram', '图表', 8),
    ('diagram-editor', '图表编辑器', 2),
    ('diagramming', '绘图', 4),
    ('dialog', '对话框', 2),
    ('diary', '日记', 1),
    ('digital-library', '数字代码库', 2),
    ('directive', '指令', 7),
    ('directory', '目录', 15),
    ('directory-cleaning', '目录清理', 1),
    ('disable', '禁用', 1),
    ('discount', '折扣', 1),
    ('discovery', '发现', 5),
    ('discussion', '讨论', 2),
    ('disk-space', '磁盘太空', 1),
    ('distributed', '分布式', 2),
    ('distributed-web', '分布式 Web', 1),
    ('document-conversion', '文档转换', 1),
    ('document-management', '文档管理', 1),
    ('document-sync', '文档同步', 1),
    ('document-translation', '文档翻译', 1),
    ('documentary', '纪录片', 1),
    ('domain-driven-design', '领域驱动设计', 10),
    ('download', '下载', 8),
    ('download-link', '下载链接', 1),
    ('drag-and-drop', '拖拽', 17),
    ('drag-detection', '拖拽检测', 1),
    ('drawing', '绘图', 6),
    ('duplicate-code', '重复代码', 1),
    ('dynamic-components', '动态组件', 3),
    ('dynamic-loading', '动态加载', 3),
    ('e2e-testing', '端到端测试', 3),
    ('editor-integration', '编辑器集成', 1),
    ('education', '教育', 1),
    ('educational', '教育', 3),
    ('effect', '效果', 4),
    ('efficient-development', '高效开发', 1),
    ('email', '邮件', 3),
    ('email-service', '邮件服务', 1),
    ('embed', '嵌入', 1),
    ('emoji', '表情', 3),
    ('emulator', '模拟器', 1),
    ('encoder', '编码器', 1),
    ('encoding', '编码', 4),
    ('encryption', '加密', 5),
    ('enterprise', '企业', 11),
    ('error-handling', '错误处理', 5),
    ('error-resolution', '错误分辨率', 1),
    ('error-tracking', '错误追踪', 1),
    ('essay', '文章', 1),
    ('event', '事件', 5),
    ('examples', '示例', 9),
    ('exchange', '交易所', 3),
    ('explainer', '解读', 1),
    ('explanation', '讲解', 2),
    ('export', '导出', 1),
    ('extension', '扩展', 1),
    ('fake-identity', '虚拟身份', 1),
    ('faq', '常见问题', 2),
    ('features', '功能', 3),
    ('file-conversion', '文件转换', 1),
    ('file-download', '文件下载', 2),
    ('file-history', '文件历史', 1),
    ('file-input', '文件 input', 1),
    ('file-management', '文件管理', 2),
    ('file-search', '文件搜索', 2),
    ('file-sharing', '文件分享', 3),
    ('file-sorting', '文件排序', 1),
    ('file-storage', '文件存储', 2),
    ('file-sync', '文件同步', 1),
    ('file-system', '文件系统', 1),
    ('file-upload', '文件上传', 6),
    ('filter', '筛选器', 3),
    ('filtering', '筛选', 1),
    ('finance', '金融', 3),
    ('financial-chart', '金融图表', 2),
    ('fingerprinting', '指纹识别', 3),
    ('flow-designer', '流程设计师', 1),
    ('flowchart', '流程图', 6),
    ('flowchart-editor', '流程图编辑器', 1),
    ('font', '字体', 8),
    ('font-converter', '字体转换器', 1),
    ('font-generator', '字体生成器', 1),
    ('font-management', '字体管理', 1),
    ('font-tool', '字体工具', 1),
    ('footer', '页脚', 2),
    ('form-validation', '表单校验', 6),
    ('format', '格式', 2),
    ('formatter', '格式化工具', 2),
    ('formatting', '格式化', 4),
    ('formula', '公式', 2),
    ('forum', '论坛', 4),
    ('framework-comparison', '框架对比', 1),
    ('framework-guide', '框架指南', 1),
    ('free-books', '免费书籍', 1),
    ('free-download', '免费下载', 1),
    ('free-email', '免费邮件', 1),
    ('free-icons', '免费 icons', 5),
    ('free-image-hosting', '免费图像托管', 3),
    ('free-images', '免费图像', 2),
    ('free-proxy', '免费代理', 4),
    ('frontend-architecture', '前端架构', 1),
    ('frontend-books', '前端书籍', 2),
    ('frontend-development', '前端开发', 1),
    ('frontend-interview', '前端面试', 3),
    ('frontend-tooling', '前端工具链', 1),
    ('full-text-search', '全文搜索', 2),
    ('fullscreen', '全屏', 2),
    ('functional-components', '函数式组件', 1),
    ('functional-programming', '函数式编程', 9),
    ('funding', '资助', 1),
    ('fundraising', '融资', 1),
    ('fuzzy-search', '模糊搜索', 2),
    ('gallery', '画廊', 4),
    ('game', '游戏', 3),
    ('game-development', '游戏开发', 1),
    ('game-map', '游戏地图', 1),
    ('generative-ai', '生成式 AI', 1),
    ('generator', '生成器', 7),
    ('geographic', '地理', 2),
    ('geography', '地理', 1),
    ('gesture', '手势', 2),
    ('gradient', '渐变', 6),
    ('graph', '图', 4),
    ('graphic-design', '平面设计', 2),
    ('grayscale-release', '灰度发布', 1),
    ('guide-generator', '指南生成器', 1),
    ('guidelines', '规范', 1),
    ('handbook', '手册', 2),
    ('hardware-wallet', '硬件钱包', 1),
    ('hashing', '哈希', 1),
    ('header', '页头', 2),
    ('headless', '无头', 2),
    ('helpers', '辅助工具', 2),
    ('hierarchical-chart', '分层图表', 1),
    ('hierarchical-memory', '分层记忆', 1),
    ('highlight', '高亮', 2),
    ('highlighting', '高亮', 5),
    ('history', '历史', 5),
    ('home-design', '家庭设计', 1),
    ('home-server', '家庭服务器', 1),
    ('hosting', '托管', 5),
    ('icon-collection', 'icon 合集', 1),
    ('icon-library', 'icon 库', 7),
    ('icon-search', 'icon 搜索', 1),
    ('identity-card', '身份卡片', 1),
    ('illustrated', '图解', 1),
    ('illustration', '插画', 7),
    ('illustration-builder', '插画构建器', 1),
    ('image', '图像', 6),
    ('image-compression', '图像压缩', 3),
    ('image-fallback', '图像降级', 1),
    ('image-hosting', '图床', 5),
    ('image-library', '图像代码库', 1),
    ('image-management', '图像管理', 2),
    ('image-optimization', '图像优化', 2),
    ('image-pull', '图像下拉', 1),
    ('image-resize', '图像 resize', 1),
    ('image-search', '图像搜索', 1),
    ('image-service', '图像服务', 1),
    ('image-sync', '图像同步', 1),
    ('image-upscaling', '图像放大', 4),
    ('immutability', '不可变性', 1),
    ('immutable', '不可变', 4),
    ('implementation', '实现', 2),
    ('indentation', '缩进', 1),
    ('infinite-scroll', '无限滚动', 2),
    ('infrastructure', '基础设施', 1),
    ('infrastructure-detection', '基础设施检测', 1),
    ('input-control', 'input 控制', 2),
    ('input-formatting', 'input 格式化', 4),
    ('input-styling', 'input 样式', 1),
    ('inspiration', '灵感', 4),
    ('installation', '安装', 6),
    ('integration', '集成', 6),
    ('interaction', '交互', 1),
    ('interactive', '交互式', 9),
    ('interactivity', '交互', 1),
    ('interface', '接口', 2),
    ('international', '国际', 2),
    ('interoperability', '互操作性', 3),
    ('interpreter', '解释器', 1),
    ('interview', '面试', 3),
    ('investigation', '调研', 1),
    ('issue', '问题', 2),
    ('journal', '期刊', 1),
    ('knowledge-base', '知识库', 6),
    ('knowledge-graph', '知识图谱', 2),
    ('knowledge-map', '知识地图', 1),
    ('landing-page', '落地页面', 5),
    ('language', '语言', 3),
    ('language-learning', '语言学习', 2),
    ('language-server', '语言服务器', 2),
    ('large-file', '大型文件', 1),
    ('launcher', '启动器', 1),
    ('lazy-loading', '懒加载', 4),
    ('learning', '学习', 6),
    ('learning-community', '学习社区', 1),
    ('learning-path', '学习路径', 2),
    ('learning-platform', '学习平台', 1),
    ('legacy', '遗留', 1),
    ('lending', '借贷', 3),
    ('library-directory', '代码库目录', 1),
    ('library-hosting', '代码库托管', 1),
    ('library-list', '代码库列表', 2),
    ('library-recommendation', '代码库推荐', 1),
    ('lightweight', '轻量', 8),
    ('linting', '代码检查', 14),
    ('list', '列表', 18),
    ('live-editor', '实时编辑器', 1),
    ('live-preview', '实时 preview', 1),
    ('live-streaming', '实时流媒体', 1),
    ('loading', '加载', 2),
    ('local-development', '本地开发', 2),
    ('local-memory', '本地记忆', 2),
    ('logging', '日志', 3),
    ('login', '登录', 2),
    ('logo-design', 'Logo 设计', 2),
    ('logo-generator', 'Logo 生成器', 3),
    ('logos', 'Logo', 2),
    ('lookup', '查询', 1),
    ('machine-learning', '机器学习', 4),
    ('magazine', '杂志', 2),
    ('mainnet', '主网', 3),
    ('maintenance', '维护', 1),
    ('management', '管理', 1),
    ('map', '地图', 3),
    ('market-data', '市场数据', 4),
    ('marketplace', '市场', 7),
    ('math', '数学', 6),
    ('media', '媒体', 2),
    ('media-conversion', '媒体转换', 1),
    ('memory', '记忆', 2),
    ('memory-analysis', '记忆分析', 1),
    ('memory-platform', '记忆平台', 1),
    ('merchant', '商户', 1),
    ('merge', '合并', 2),
    ('metrics', '指标', 3),
    ('micro-frontend', '微前端', 7),
    ('microservices', '微服务', 4),
    ('migration', '迁移', 3),
    ('migration-guide', '迁移指南', 1),
    ('mindmap', '思维导图', 5),
    ('mirror', '镜像', 6),
    ('mobile-testing', '移动端测试', 1),
    ('mock-data', 'mock 数据', 3),
    ('mock-image', 'mock 图像', 1),
    ('mock-service-worker', 'mock 服务工作线程', 1),
    ('modal-editor', 'modal 编辑器', 2),
    ('model-aggregation', '模型聚合', 1),
    ('model-comparison', '模型对比', 1),
    ('model-search', '模型搜索', 4),
    ('modeling', '建模', 1),
    ('modular', '模块化', 2),
    ('modular-framework', '模块化框架', 1),
    ('modules', '模块', 5),
    ('monitoring', '监控', 3),
    ('motion', '动效', 3),
    ('movie-download', '电影下载', 1),
    ('movie-recommendation', '电影推荐', 1),
    ('movie-streaming', '电影流媒体', 1),
    ('movies', '电影', 1),
    ('multi-agent', '多 agent', 1),
    ('multi-language', '多语言', 3),
    ('multi-line', '多行', 2),
    ('multi-model', '多模型', 1),
    ('multi-process', '多进程', 1),
    ('multi-provider', '多服务商', 1),
    ('multi-touch', '多触摸', 1),
    ('multimedia', '多媒体', 1),
    ('natural-language', '自然语言', 1),
    ('navigation', '导航', 14),
    ('network', '网络', 9),
    ('network-issue', '网络问题', 1),
    ('networking', '网络', 5),
    ('news', '资讯', 7),
    ('news-aggregator', '资讯聚合器', 2),
    ('newsletter', '周刊', 3),
    ('no-build', '无 build', 1),
    ('no-code', '无代码', 7),
    ('node-editor', '节点编辑器', 2),
    ('node-list', '节点列表', 1),
    ('node-modules', '节点模块', 1),
    ('node-provider', '节点服务商', 5),
    ('node-service', '节点服务', 1),
    ('note-sharing', '笔记分享', 1),
    ('note-taking', '笔记', 6),
    ('notification', '通知', 4),
    ('number-conversion', '数字转换', 2),
    ('number-formatting', '数字格式化', 7),
    ('object-diff', '对象 diff', 2),
    ('object-validation', '对象校验', 1),
    ('observability', '可观测性', 1),
    ('observable', '可观察对象', 2),
    ('observer-pattern', '观察者模式', 1),
    ('offline', '离线', 8),
    ('onboarding', '上手引导', 2),
    ('online-compiler', '在线编译器', 1),
    ('online-converter', '在线转换器', 1),
    ('online-database', '在线数据库', 1),
    ('online-editor', '在线编辑器', 2),
    ('online-learning', '在线学习', 1),
    ('online-library', '在线代码库', 1),
    ('online-reading', '在线阅读', 1),
    ('open-access', '开放访问', 2),
    ('operating-system', '操作系统', 2),
    ('operators', '运算符', 2),
    ('opinion', '观点', 3),
    ('optimization', '优化', 9),
    ('organization', '组织', 1),
    ('organization-chart', '组织图表', 2),
    ('orientation', '方向', 1),
    ('overflow', '溢出', 2),
    ('overflow-detection', '溢出检测', 1),
    ('overlay', '覆盖层', 2),
    ('overview', '概览', 4),
    ('package-analysis', '包分析', 1),
    ('package-comparison', '包对比', 2),
    ('package-development', '包开发', 4),
    ('package-management', '包管理', 1),
    ('packaging-design', '包装设计', 1),
    ('page-builder', '页面构建器', 2),
    ('page-orientation', '页面方向', 2),
    ('page-visibility', '页面可见性', 1),
    ('paid', '付费', 2),
    ('painting', '绘画', 1),
    ('panorama', '全景', 2),
    ('parallelism', '并行', 1),
    ('parser', '解析器', 7),
    ('partial-merge', '部分合并', 1),
    ('particles', '粒子', 2),
    ('password', '密码', 1),
    ('patch', '补丁', 2),
    ('patching', '补丁', 2),
    ('path', '路径', 1),
    ('pattern', '模式', 4),
    ('pattern-generator', '模式生成器', 1),
    ('payment', '支付', 10),
    ('payment-gateway', '支付网关', 1),
    ('performance-monitor', '性能监控器', 1),
    ('performance-optimization', '性能优化', 1),
    ('permission-system', '权限系统', 1),
    ('permissions', '权限', 1),
    ('persistence', '持久化', 1),
    ('personal', '个人', 3),
    ('personal-note', '个人笔记', 1),
    ('philosophy', '哲学', 1),
    ('phishing', '钓鱼', 1),
    ('photo-editing', '照片编辑', 1),
    ('photography', '摄影', 1),
    ('picker', '选择器', 1),
    ('placeholder', '占位符', 2),
    ('platform-comparison', '平台对比', 1),
    ('platform-development', '平台开发', 1),
    ('player', '播放器', 2),
    ('plugin-architecture', '插件架构', 1),
    ('plugin-repository', '插件仓库', 1),
    ('portfolio', '作品集', 3),
    ('portfolio-tracker', '作品集追踪器', 4),
    ('position-sticky', '定位吸附', 2),
    ('poster', '海报', 1),
    ('practice', '实践', 2),
    ('precision', '精度', 2),
    ('prediction-market', '预测市场', 1),
    ('prefetch', '预取', 2),
    ('preflight', '预检', 1),
    ('premium-icons', '高级 icons', 1),
    ('presentation', '演示文稿', 8),
    ('preset', '预设', 2),
    ('preview-environment', 'preview 环境', 1),
    ('price-chart', '价格图表', 1),
    ('price-monitor', '价格监控器', 1),
    ('price-tracker', '价格追踪器', 4),
    ('price-tracking', '价格追踪', 1),
    ('pricing', '定价', 3),
    ('principles', '原则', 2),
    ('print', '打印', 6),
    ('printing', '打印', 6),
    ('privacy', '隐私', 13),
    ('private-cloud', '私有云', 1),
    ('private-registry', '私有 registry', 2),
    ('process', '进程', 1),
    ('product-page', '产品页面', 1),
    ('production', '生产环境', 1),
    ('productivity', '效率', 6),
    ('profiling', '性能分析', 4),
    ('programmer', '程序员', 2),
    ('programming', '编程', 9),
    ('programming-assistant', '编程助手', 1),
    ('programming-books', '编程书籍', 3),
    ('project', '项目', 6),
    ('project-directory', '项目目录', 1),
    ('project-management', '项目管理', 3),
    ('prompt', '提示词', 2),
    ('prompt-engineering', '提示词工程', 1),
    ('prompt-optimization', '提示词优化', 1),
    ('proposals', '提案', 3),
    ('protocol', '协议', 11),
    ('prototype', '原型', 1),
    ('prototyping', '原型设计', 3),
    ('provider', '服务商', 1),
    ('provider-discovery', '服务商发现', 1),
    ('proxy-list', '代理列表', 4),
    ('proxy-provider', '代理服务商', 2),
    ('proxy-registry', '代理 registry', 1),
    ('proxy-service', '代理服务', 4),
    ('public-domain', '公共领域', 1),
    ('public-proxy', '公共代理', 1),
    ('push', '推送', 1),
    ('question', '问题', 2),
    ('random-data', '随机数据', 1),
    ('ranking', '排名', 2),
    ('reactive-programming', '响应式编程', 7),
    ('reading', '阅读', 1),
    ('realtime', '实时', 12),
    ('realtime-collaboration', '实时协作', 2),
    ('recommendation', '推荐', 7),
    ('recursion', '递归', 1),
    ('refactoring', '重构', 2),
    ('refund', '退款', 1),
    ('release', '发布', 1),
    ('remote-component', '远程组件', 4),
    ('rendering', '渲染', 4),
    ('replication', '复制', 1),
    ('repository', '仓库', 3),
    ('research', '研究', 3),
    ('residential-proxy', '住宅代理', 3),
    ('resource-discovery', '资源发现', 1),
    ('resource-list', '资源列表', 8),
    ('resource-search', '资源搜索', 1),
    ('resource-sharing', '资源分享', 3),
    ('responsive', '响应式', 5),
    ('responsive-design', '响应式设计', 4),
    ('resume', '简历', 1),
    ('reuse', '复用', 1),
    ('reverse-engineering', '逆向工程', 3),
    ('review', '评审', 1),
    ('rewards', '奖励', 1),
    ('rich-text-editor', '富文本编辑器', 10),
    ('risk-analysis', '风险分析', 1),
    ('roleplay', '角色扮演', 1),
    ('router', '路由器', 3),
    ('routing', '路由', 6),
    ('runtime', '运行时', 2),
    ('sandbox', '沙箱', 4),
    ('scaffolding', '脚手架', 3),
    ('scam-analysis', '诈骗分析', 1),
    ('scanner', '扫描器', 2),
    ('scheduler', '调度器', 2),
    ('schema', '模式', 4),
    ('schema-validation', '模式校验', 9),
    ('science', '科学', 1),
    ('screenshot', '截图', 3),
    ('scripting', '脚本', 2),
    ('scripts', '脚本', 3),
    ('scroll-sync', 'scroll 同步', 2),
    ('scrolling', '滚动', 2),
    ('search', '搜索', 8),
    ('search-engine', '搜索引擎', 8),
    ('search-highlight', '搜索高亮', 3),
    ('security-analysis', '安全分析', 1),
    ('security-guide', '安全指南', 1),
    ('security-review', '安全评审', 1),
    ('select', '选择器', 4),
    ('selectors', '选择器', 2),
    ('self-hosted', '自托管', 8),
    ('self-study', '自托管留学', 1),
    ('series', '系列', 1),
    ('server-configuration', '服务器配置', 1),
    ('server-management', '服务器管理', 2),
    ('server-setup', '服务器配置', 1),
    ('server-state', '服务器状态', 1),
    ('service', '服务', 7),
    ('service-worker', '服务工作线程', 2),
    ('session', '会话', 4),
    ('session-history', '会话历史', 1),
    ('session-memory', '会话记忆', 1),
    ('setup', '配置', 6),
    ('shape', '形状', 3),
    ('sharing', '分享', 4),
    ('showcase', '案例展示', 2),
    ('simulation', '模拟', 2),
    ('skeleton', '骨架屏', 3),
    ('skill-registry', 'skill registry', 1),
    ('skills-management', 'skill 管理', 2),
    ('slides', '幻灯片', 8),
    ('smooth-scroll', '平滑 scroll', 1),
    ('social-media', '社交媒体', 4),
    ('social-media-preview', '社交媒体 preview', 1),
    ('software-directory', '软件目录', 1),
    ('software-download', '软件下载', 3),
    ('software-engineering', '软件工程', 2),
    ('sorting', '排序', 2),
    ('source-code', '源代码', 5),
    ('source-code-analysis', '源码代码分析', 3),
    ('space-images', '太空图像', 1),
    ('specification', '规范', 6),
    ('spreadsheet', '电子表格', 6),
    ('standard', '标准', 4),
    ('standard-library', '标准代码库', 1),
    ('standard-map', '标准地图', 1),
    ('starter', '启动模板', 2),
    ('startup-time', '启动时间', 1),
    ('startups', '创业公司', 1),
    ('state-machine', '状态机', 7),
    ('static-analysis', '静态分析', 1),
    ('static-assets', '静态素材', 4),
    ('static-site', '静态网站', 3),
    ('sticky-header', '吸附页头', 2),
    ('storage', '存储', 7),
    ('streaming', '流媒体', 3),
    ('style-checker', '样式检查器', 1),
    ('style-guide', '样式指南', 3),
    ('styling', '样式', 2),
    ('styling-system', '样式系统', 1),
    ('submit', '提交', 1),
    ('subscription', '订阅', 2),
    ('subscription-service', '订阅服务', 1),
    ('subscription-sharing', '订阅分享', 1),
    ('summarization', '摘要', 1),
    ('summary', '摘要', 1),
    ('super-resolution', '超分辨率', 2),
    ('survey', '调研', 5),
    ('sync', '同步', 3),
    ('synchronization', '同步', 2),
    ('syntax', '语法', 1),
    ('syntax-highlighting', '语法高亮', 6),
    ('system-design', '系统设计', 2),
    ('tag-input', '标签 input', 1),
    ('team', '团队', 1),
    ('technical-documentation', '技术文档', 1),
    ('technology', '技术', 2),
    ('template-download', '模板下载', 1),
    ('template-engine', '模板引擎', 16),
    ('template-language', '模板语言', 1),
    ('template-rendering', '模板渲染', 1),
    ('templating', '模板', 2),
    ('temporary-email', '临时邮件', 2),
    ('terminal', '终端', 9),
    ('terminal-emulator', '终端模拟器', 1),
    ('test-data', '测试数据', 1),
    ('test-data-generator', '测试数据生成器', 1),
    ('text', '文本', 3),
    ('text-control', '文本控制', 1),
    ('text-conversion', '文本转换', 1),
    ('text-diff', '文本 diff', 4),
    ('text-editor', '文本编辑器', 5),
    ('text-highlight', '文本高亮', 6),
    ('text-highlighting', '文本高亮', 1),
    ('text-logo', '文本 Logo', 1),
    ('text-object', '文本对象', 1),
    ('text-overflow', '文本溢出', 4),
    ('text-processing', '文本处理', 12),
    ('text-recognition', '文字识别', 5),
    ('text-sharing', '文本分享', 1),
    ('text-truncation', '文本截断', 1),
    ('theme-editor', 'theme 编辑器', 1),
    ('theory', '理论', 1),
    ('thread', '线程', 1),
    ('throttle', '节流', 1),
    ('time', '时间', 2),
    ('timeline', '时间线', 2),
    ('timezone', '时区', 1),
    ('tips', '技巧', 7),
    ('token-compression', 'token 压缩', 1),
    ('token-icons', 'token icons', 1),
    ('token-list', 'token 列表', 2),
    ('token-management', 'token 管理', 1),
    ('token-trading', 'token 交易', 1),
    ('tool-aggregation', '工具聚合', 1),
    ('tool-comparison', '工具对比', 1),
    ('tool-discovery', '工具发现', 1),
    ('tool-setup', '工具配置', 1),
    ('tooling', '工具链', 1),
    ('touch', '触摸', 2),
    ('tracking', '追踪', 1),
    ('trading', '交易', 8),
    ('transaction-monitoring', '交易监控', 1),
    ('transactional-email', '事务型邮件', 1),
    ('transformer', '转换器', 1),
    ('transitions', '过渡', 1),
    ('translation', '翻译', 9),
    ('transparency', '透明度', 1),
    ('trend-analysis', '趋势分析', 1),
    ('trends', '趋势', 1),
    ('triangle', '三角形', 1),
    ('truncation', '截断', 2),
    ('typography', '排版', 5),
    ('unit-conversion', '单位转换', 1),
    ('update', '更新', 1),
    ('update-error', '更新错误', 1),
    ('upgrade', '升级', 2),
    ('upscaling', '放大', 1),
    ('user-agent', '用户 agent', 1),
    ('user-experience', '用户体验', 1),
    ('user-notification', '用户通知', 1),
    ('user-onboarding', '用户上手引导', 1),
    ('utility', '实用工具', 7),
    ('utility-library', '实用工具代码库', 1),
    ('utils', '实用工具', 1),
    ('validate', '校验', 1),
    ('validation', '校验', 9),
    ('validator', '校验器', 1),
    ('variables', '变量', 1),
    ('vector', '矢量', 8),
    ('vector-editor', '矢量编辑器', 1),
    ('vector-search', '矢量搜索', 1),
    ('verification', '验证', 1),
    ('version-control', '版本控制', 1),
    ('versioning', '版本管理', 2),
    ('video', '视频', 3),
    ('video-conversion', '视频转换', 1),
    ('video-editing', '视频编辑', 1),
    ('video-library', '视频代码库', 1),
    ('video-streaming', '视频流媒体', 1),
    ('video-tutorial', '视频教程', 1),
    ('viewer', '查看器', 1),
    ('virtual-card', '虚拟卡片', 2),
    ('virtual-machine', '虚拟机', 1),
    ('virtual-scroll', '虚拟 scroll', 4),
    ('visibility', '可见性', 1),
    ('visual-builder', '可视化构建器', 5),
    ('visual-editing', '可视化编辑', 2),
    ('visual-editor', '可视化编辑器', 2),
    ('visual-guide', '可视化指南', 1),
    ('visual-layout', '可视化 layout', 1),
    ('visual-layout-editor', '可视化 layout 编辑器', 1),
    ('visual-programming', '可视化编程', 5),
    ('visualization', '可视化', 12),
    ('vocabulary', '词汇', 2),
    ('voting', '投票', 1),
    ('wallet', '钱包', 10),
    ('wallet-integration', '钱包集成', 3),
    ('wallpaper', '壁纸', 3),
    ('watermark', '水印', 8),
    ('waveform', '波形', 2),
    ('weak-typing', '弱打字', 1),
    ('web-app', 'Web 应用', 15),
    ('web-app-builder', 'Web 应用构建器', 1),
    ('web-builder', 'Web 构建器', 1),
    ('web-components', 'Web 组件', 17),
    ('web-debugging', 'Web 调试', 1),
    ('web-design', 'Web 设计', 2),
    ('web-development', 'Web 开发', 10),
    ('web-development-news', 'Web 开发资讯', 1),
    ('web-development-weekly', 'Web 开发周刊', 1),
    ('web-directory', 'Web 目录', 2),
    ('web-framework', 'Web 框架', 5),
    ('web-interaction', 'Web 交互', 1),
    ('web-page', 'Web 页面', 1),
    ('web-performance', 'Web 性能', 8),
    ('web-platform', 'Web 平台', 1),
    ('web-screenshot', 'Web 截图', 1),
    ('web-search', 'Web 搜索', 2),
    ('web-security', 'Web 安全', 4),
    ('web-storage', 'Web 存储', 6),
    ('web-testing', 'Web 测试', 1),
    ('website', '网站', 4),
    ('website-analysis', '网站分析', 2),
    ('website-recommendation', '网站推荐', 1),
    ('weekly', '周刊', 6),
    ('white-box-testing', '白盒测试', 1),
    ('whiteboard', '白板', 5),
    ('wiki', '百科', 3),
    ('words', '单词', 1),
    ('work', '工作', 1),
    ('workaround', '变通方案', 4),
    ('workflow', '工作流', 9),
    ('workspace', '工作区', 2),
    ('wrapper', '封装', 4),
    ('writing', '写作', 1),
    ('zero-dependency', '零依赖', 4),
    ('zero-runtime', '零运行时', 2),
    ('architecture-evolution', '架构设计演化', 1),
    ('baidu', '百度', 3),
    ('baidu-cloud', '百度云', 1),
    ('baidu-developer', '百度开发者', 1),
    ('baidu-netdisk', '百度网盘', 1),
    ('crypto-news', '加密新闻', 6),
    ('crypto-resources', '加密资源', 1),
    ('ebook', '电子书', 13),
    ('ebook-download', '电子书下载', 6),
    ('ebook-library', '电子书库', 2),
    ('ebook-website', '电子书网站', 1),
    ('shopping-cart', '购物车', 1),
    ('voice-cloning', '声音克隆', 1),
    ('wallet-connection', '钱包连接', 5),
    ('web-authentication', '网页认证', 1),
    ('web-automation', '网站自动化', 1),
    ('web-dev-resources', 'web-dev 资源', 1),
    ('web-fonts', '网页字体', 3),
    ('website-templates', '网站模板', 1),
    ('wechat', '微信', 2),
    ('wechat-login', '微信登录', 1),
    ('wechat-mini-program', '微信小程序', 12),
    ('wechat-pay', '微信支付', 5),
    ('white-screen', '白屏', 1),
    ('xunfei', '讯飞', 1),
    ('yellow-paper', '黄页', 1),
    ('yuque', '语雀', 2),
    ('zhihu', '知乎', 3);

CREATE TEMP TABLE migration_assert (
    value INTEGER NOT NULL CHECK (value = 1)
);

INSERT INTO migration_assert
SELECT count(*) = 989
FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

INSERT INTO migration_assert
SELECT count(*) = 0
FROM tag_localization_map mapping
WHERE mapping.expected_count != (
    SELECT count(*)
    FROM bookmark_tags bt
    JOIN tags source ON source.id = bt.tag_id
    WHERE source.name = mapping.source
);

INSERT INTO migration_assert
SELECT count(*) = 0
FROM tag_localization_map
WHERE source = target OR target != trim(target) OR target = '' OR instr(target, ',') > 0;

INSERT OR IGNORE INTO tags(name)
SELECT DISTINCT target FROM tag_localization_map;

INSERT INTO bookmark_tags(bookmark_id, tag_id)
SELECT bt.bookmark_id, target.id
FROM tag_localization_map mapping
JOIN tags source ON source.name = mapping.source
JOIN bookmark_tags bt ON bt.tag_id = source.id
JOIN tags target ON target.name = mapping.target
ON CONFLICT(bookmark_id, tag_id) DO NOTHING;

DELETE FROM bookmark_tags
WHERE tag_id IN (
    SELECT id FROM tags WHERE name IN (SELECT source FROM tag_localization_map)
);

DELETE FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

DELETE FROM bookmarks_fts;
INSERT INTO bookmarks_fts(rowid, url, title, description, tags)
SELECT b.id, b.url, b.title, b.description,
       coalesce((
           SELECT group_concat(name, ' ')
           FROM (
               SELECT t.name AS name
               FROM bookmark_tags bt
               JOIN tags t ON t.id = bt.tag_id
               WHERE bt.bookmark_id = b.id
               ORDER BY t.name
           )
       ), '')
FROM bookmarks b;

INSERT INTO migration_assert SELECT count(*) = 2173 FROM bookmarks;
INSERT INTO migration_assert SELECT count(*) = 2191 FROM tags;
INSERT INTO migration_assert SELECT count(*) = 10514 FROM bookmark_tags;
INSERT INTO migration_assert
SELECT count(*) = 0
FROM bookmarks b
WHERE NOT EXISTS (
    SELECT 1 FROM bookmark_tags bt WHERE bt.bookmark_id = b.id
);
INSERT INTO migration_assert
SELECT count(*) = 0
FROM tags t
WHERE NOT EXISTS (
    SELECT 1 FROM bookmark_tags bt WHERE bt.tag_id = t.id
);
INSERT INTO migration_assert SELECT count(*) = 0 FROM pragma_foreign_key_check;
INSERT INTO migration_assert SELECT count(*) = 2173 FROM bookmarks_fts;
INSERT INTO migration_assert
SELECT count(*) = 0
FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

COMMIT;
