.bail on
.timeout 10000

PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

CREATE TEMP TABLE tag_localization_map (
    source TEXT PRIMARY KEY,
    target TEXT NOT NULL,
    expected_count INTEGER NOT NULL
);

INSERT INTO tag_localization_map(source, target, expected_count) VALUES
    ('accounting-js', '会计 JS', 1),
    ('anime-js', '动漫 JS', 1),
    ('app-creator', '应用创建工具', 1),
    ('app-deeplink', 'app唤起', 2),
    ('arakawa-yui', 'arakawa yui', 1),
    ('asset-swap', '资产兑换', 1),
    ('australia', '澳大利亚', 1),
    ('authkit', '鉴权', 1),
    ('auto-restart', '自动重启', 1),
    ('auto-save', '自动保存', 1),
    ('autocomplete', '自动补全', 4),
    ('autofill', '自动填充', 1),
    ('automated-eda', 'EDA 自动化', 1),
    ('background-removal', '抠图', 5),
    ('baidu-template', '百度模板引擎', 1),
    ('bean-validation', 'Bean 校验', 1),
    ('beginner-friendly', '新手友好', 1),
    ('benchmark', '基准测试', 1),
    ('bezier', '贝塞尔', 2),
    ('big-integer', '大整数', 1),
    ('big-screen', '大屏', 1),
    ('blending', '混合', 1),
    ('blockchain-basics', '区块链基础', 1),
    ('blockchain-bridge', '跨链桥', 1),
    ('blockchain-community', '区块链社区', 1),
    ('blockchain-data', '区块链数据', 1),
    ('blockchain-demo', '区块链演示', 1),
    ('blockchain-explorer', '区块链浏览器', 3),
    ('blockchain-infrastructure', '区块链基础设施', 2),
    ('blockchain-media', '区块链媒体', 2),
    ('blockchain-news', '区块链新闻', 4),
    ('blockchain-security', '区块链安全', 2),
    ('blockchain-tools', '区块链工具', 1),
    ('blocking-queue', '阻塞队列', 1),
    ('bn-js', 'bn.js', 1),
    ('book-collection', '书籍合集', 3),
    ('bookmark-collection', '书签合集', 1),
    ('boolean-expression', '布尔表达式', 1),
    ('box-shadow', 'CSS 阴影', 1),
    ('brave-search', 'Brave Search', 1),
    ('broadcast-channel', 'Broadcast Channel', 2),
    ('browser-based', '浏览器端', 2),
    ('browser-events', '浏览器事件', 1),
    ('browser-internals', '浏览器原理', 1),
    ('browser-properties', '浏览器属性', 1),
    ('bug-prevention', 'bug预防', 1),
    ('build-warning', '构建警告', 1),
    ('building-blocks', '构建块', 1),
    ('bundle-size', '打包体积', 3),
    ('business-plan', '商业计划', 1),
    ('business-rules', '商业规则', 1),
    ('canvas', 'Canvas', 15),
    ('canvas-fingerprint', 'Canvas 指纹', 1),
    ('carbon-design-system', 'Carbon Design System', 1),
    ('casino', '赌场', 1),
    ('cell-edit', '单元格编辑', 1),
    ('censorship-circumvention', '审查规避', 3),
    ('chain-id', '链 ID', 1),
    ('chinese-calligraphy', '书法', 1),
    ('chinese-classical-texts', '中国古籍', 1),
    ('chinese-colors', '中国传统色', 1),
    ('chinese-entertainment', '国内影视', 1),
    ('chinese-journalism', '中国新闻', 1),
    ('chinese-literature', '中国文学', 1),
    ('chunked-upload', '分片上传', 1),
    ('claims', '薅', 1),
    ('class-variance-authority', '样式变体管理', 1),
    ('client-side', '客户端', 2),
    ('client-side-routing', '客户端路由', 1),
    ('client-side-storage', '客户端存储', 1),
    ('clipboard-manager', '剪贴板管理器', 1),
    ('cloud-acceleration', '云加速', 1),
    ('cloud-drive', '网盘搜索', 1),
    ('code-exploration', '代码探索', 1),
    ('code-importance', '代码重要性', 1),
    ('code-intelligence', '智能编程', 2),
    ('code-lines', '代码行', 1),
    ('code-protection', '代码保护', 2),
    ('code-snippet', '代码片段', 1),
    ('code-splitting', '代码分割', 1),
    ('code-statistics', '代码统计', 1),
    ('codebase-indexing', '代码库索引', 1),
    ('codec', '编解码器', 1),
    ('color-manipulation', '颜色操作', 2),
    ('color-palette', '颜色调色板', 7),
    ('color-palette-generator', '颜色调色板生成器', 1),
    ('color-scheme', '颜色方案', 2),
    ('color-scheme-generator', '颜色方案生成', 1),
    ('command-menu', '命令菜单', 1),
    ('commercial-use', '商业用途', 1),
    ('competitor-research', '竞品研究', 1),
    ('component-creation', '组件创作', 1),
    ('component-generation', '组件生成', 1),
    ('component-lifecycle', '组件生命周期', 1),
    ('component-loader', '组件加载', 4),
    ('composables', '组合式函数', 3),
    ('computer-vision', '计算机视觉', 1),
    ('concurrent-execution', '并发执行', 1),
    ('consulting', '咨询', 1),
    ('container-queries', '容器查询', 2),
    ('content-aware', '内容感知', 2),
    ('content-driven', '内容驱动', 1),
    ('contract-addresses', '合约地址', 1),
    ('conventional-commits', '约定式commits', 2),
    ('copy-protection', '拷贝保护', 1),
    ('crack', '破解', 1),
    ('cracked-software', '破解软件', 1),
    ('crash-dump', '崩溃转储', 1),
    ('credit-card-generator', '信用卡生成器', 1),
    ('cross-border-ecommerce', '跨境电商', 1),
    ('cross-chain', '跨链', 8),
    ('cross-origin', '跨域', 2),
    ('cross-origin-image', '跨域图片', 2),
    ('cross-tab-communication', '跨标签页通信', 2),
    ('crypto-airdrops', '加密空投', 1),
    ('crypto-community', '加密社区', 2),
    ('crypto-data', '加密数据', 1),
    ('crypto-exchange', '加密交易所', 3),
    ('crypto-history', '加密历史', 1),
    ('crypto-media', '加密媒体', 1),
    ('crypto-timeline', '加密时间线', 1),
    ('crypto-tools', '加密工具', 3),
    ('cryptography', '密码学', 5),
    ('cs-self-learning', '计算机自学', 1),
    ('curriculum', '课程', 1),
    ('cursor', '光标', 5),
    ('cursor-position', '光标位置', 3),
    ('custom-elements', '自定义元素', 2),
    ('custom-scrollbar', '自定义滚动条', 1),
    ('custom-snippet', '自定义代码片段', 1),
    ('daily-dev', '每日开发', 1),
    ('data-collection', '数据合集', 1),
    ('data-mocking', '数据 mock', 1),
    ('data-preparation', '数据准备', 1),
    ('data-screen', '数据大屏', 1),
    ('data-sending', '数据发送', 1),
    ('data-tools', '数据工具', 2),
    ('data-transfer', '数据传输', 2),
    ('datacenter-proxy', '数据中心代理', 2),
    ('date-parsing', '日期解析', 1),
    ('datepicker', '日期选择器', 4),
    ('decimal', '小数', 3),
    ('deep-dive', '深度解析', 1),
    ('deep-imports', '深度导入', 1),
    ('definitely-typed', 'DefinitelyTyped', 1),
    ('dependency-check', '依赖检查', 1),
    ('derivatives-trading', '衍生品交易', 1),
    ('design-tip', '设计技巧', 1),
    ('design-to-code', '设计稿转代码', 2),
    ('dev', '开发', 2),
    ('dev-diaries', '开发日记', 1),
    ('dev-server', '开发服务器', 1),
    ('developer-docs', '开发者文档', 1),
    ('developer-profile', '开发者档案', 1),
    ('developer-roadmap', '开发者路线图', 1),
    ('development-method', '开发方法', 1),
    ('development-mode', '开发模式', 1),
    ('development-toolkit', '开发工具包', 1),
    ('development-tools', '开发工具', 1),
    ('devtools', 'DevTools', 10),
    ('devtools-detection', 'DevTools 检测', 1),
    ('di-container', '依赖注入容器', 1),
    ('diffusion-models', '扩散模型', 1),
    ('digital-literacy', '数字素养', 1),
    ('directory-cleanup', '目录清理', 1),
    ('directory-jumping', '目录跳转', 2),
    ('discovery-channel', '发现频道', 1),
    ('disk-usage', '磁盘用量', 1),
    ('distributed-systems', '分布式系统', 1),
    ('document-processing', '文档处理', 3),
    ('domain-primitive', '领域原语', 2),
    ('domain-sale', '领域销售', 1),
    ('download-accelerator', '下载加速器', 2),
    ('download-stats', '下载统计', 1),
    ('dynamic-templates', '动态模板', 1),
    ('e-reader', '电子阅读器', 1),
    ('ecommerce', '电商', 5),
    ('ecosystem', '生态', 4),
    ('edge', '边缘', 3),
    ('edge-rendering', '边缘渲染', 1),
    ('element-outline', '元素outline', 1),
    ('ellipsis', '省略', 3),
    ('end-to-end-typesafety', '端到端类型安全', 2),
    ('english', '英语', 1),
    ('english-font', '英语字体', 1),
    ('english-learning', '英语学习', 1),
    ('env-var-manager', '环境变量管理器', 2),
    ('error-fix', '错误修复', 2),
    ('es-modules', 'ES 模块', 3),
    ('esoteric', '小众', 1),
    ('etymology', '词源学', 2),
    ('event-driven', '事件驱动', 1),
    ('event-emitter', '事件触发器', 2),
    ('event-handling', '事件处理', 2),
    ('event-listener', '事件监听器', 1),
    ('event-loop', '事件循环', 1),
    ('expense-management', '费用管理', 1),
    ('exposure-watch', '泄露监测', 1),
    ('expression-language', '表达式语言', 1),
    ('extensible-architecture', '可扩展架构', 1),
    ('fan-blog', '粉丝博客', 1),
    ('fantasy', '奇幻', 1),
    ('faucet', '水龙头', 9),
    ('favicon', '网站图标', 3),
    ('feature-flags', '功能开关', 1),
    ('feature-request', '功能请求', 1),
    ('fiction', '小说', 1),
    ('file-explorer', '文件浏览器', 1),
    ('file-transfer', '文件传输', 2),
    ('fill', '填充', 1),
    ('find-locate', '文件查找', 1),
    ('fintech', '金融科技', 1),
    ('fixed-column', '固定列', 2),
    ('flamegraph', '火焰图', 1),
    ('flow-based-programming', '流程式编程', 1),
    ('font-face', '字体字形', 2),
    ('free-ebooks', '免费电子书', 2),
    ('free-resources', '免费资源', 1),
    ('free-services', '免费服务', 1),
    ('free-tier', '免费层', 1),
    ('freebies', '免费资源', 1),
    ('front-end-testing', '前端测试', 1),
    ('frontend-blog', '前端博客', 1),
    ('frontend-exception', '前端异常', 1),
    ('frontend-frameworks', '前端框架', 1),
    ('fullstack', '全栈', 3),
    ('funny', '趣味', 1),
    ('fuzzy-finder', '模糊查找', 1),
    ('gambling', '博彩', 1),
    ('gas', 'Gas', 1),
    ('gas-consumption', 'Gas 消耗', 1),
    ('gas-estimation', 'Gas 估算', 1),
    ('gas-fee', 'Gas 手续费', 1),
    ('gas-tracker', 'Gas 追踪器', 1),
    ('generated-content', '生成内容', 1),
    ('generics', '泛型', 1),
    ('getting-started', '快速入门', 1),
    ('gif', 'GIF', 4),
    ('google-ai', 'Google AI', 3),
    ('google-cloud', 'Google 云', 1),
    ('google-translate', 'Google 翻译', 2),
    ('governance', '治理', 1),
    ('gpu-accelerated', 'GPU 加速', 1),
    ('gradient-boosting', '梯度提升', 2),
    ('graphing-calculator', '绘图计算器', 1),
    ('guide-collection', '指南合集', 1),
    ('hack-database', '破解数据库', 1),
    ('hand-drawn', '手绘', 4),
    ('has-pseudo-class', ':has 伪类', 1),
    ('header-grouping', '表头分组', 1),
    ('headless-cms', '无头 CMS', 1),
    ('here-document', 'Here Document', 1),
    ('hot-list', '热门榜单', 1),
    ('hover-effects', 'hover效果', 4),
    ('ie', 'IE', 10),
    ('image-accelerator', '图片加速器', 1),
    ('image-collection', '图片合集', 1),
    ('image-preloading', '图片预加载', 1),
    ('image-recognition', '图像识别', 1),
    ('image-transformation', '图片转换', 1),
    ('image-upload', '图像上传', 4),
    ('immediate-mode', '即时模式', 2),
    ('immigration', '移民', 1),
    ('inline-assembly', '内联汇编', 1),
    ('inpainting', '图像修复', 3),
    ('input-mask', '输入掩码', 3),
    ('input-method', '输入法', 1),
    ('input-value', '输入值', 1),
    ('install-size', '安装包体积', 2),
    ('instance-discovery', '实例发现', 1),
    ('intellij-idea', 'IDEA', 1),
    ('interactive-diagrams', '交互式图表', 1),
    ('interactive-docs', '交互式文档', 2),
    ('interactive-staging', '交互式暂存', 1),
    ('intercepting', '拦截', 1),
    ('interface-generation', '接口生成', 1),
    ('intermediate', '进阶', 1),
    ('internet-explorer', 'IE', 1),
    ('interview-prep', '面试准备', 3),
    ('interview-questions', '面试问题', 5),
    ('ip-check', 'IP 检查', 2),
    ('ip-geolocation', 'IP 位置', 1),
    ('ip-proxy', 'IP 代理', 1),
    ('islands-architecture', 'islands 架构', 1),
    ('japanese-actress', '日本女演员', 1),
    ('job-hunting', '工作求职', 2),
    ('k-line-chart', 'K 线图', 1),
    ('key-generation', '密钥生成', 1),
    ('keyboard-events', '键盘事件', 1),
    ('keyboard-shortcuts', '键盘快捷键', 1),
    ('landscape', '全景', 3),
    ('large-scale-app', '大型软件', 1),
    ('large-scale-systems', '大型系统', 1),
    ('layout-shift', '布局偏移', 2),
    ('learning-hub', '学习中心', 1),
    ('learning-notes', '学习笔记', 1),
    ('learning-resources', '学习资源', 2),
    ('library-collection', '代码库合集', 3),
    ('line-counting', '行计数', 1),
    ('linear-gradient', '线性渐变', 1),
    ('link-shortener', '短链工具', 4),
    ('liquid-staking', '流动性质押', 2),
    ('liquidity-locking', '流动性锁定', 1),
    ('liquidity-protocol', '流动性协议', 2),
    ('live-reload', '热重载', 1),
    ('live-tv', '直播', 1),
    ('logical-operations', '逻辑运维', 1),
    ('logo-maker', 'Logo 制作', 2),
    ('long-term-memory', '长期记忆', 1),
    ('lorem-ipsum', 'lorem ipsum', 1),
    ('lottery', '彩票', 1),
    ('low-poly', 'low poly', 1),
    ('loyalty-program', '会员忠诚度计划', 1),
    ('market-cap', '市场市值', 1),
    ('media-downloader', '媒体下载器', 1),
    ('memecoin-launchpad', 'memecoin launchpad', 1),
    ('memory-systems', '记忆系统', 1),
    ('merged-headers', '合并请求头', 1),
    ('meta-tags', 'meta 标签', 1),
    ('metadata-badges', '元数据徽章', 1),
    ('metaprogramming', '元编程', 2),
    ('microsoft', '微软', 2),
    ('mime-type', 'MIME 类型', 2),
    ('mini-nvim', 'mini nvim', 1),
    ('minifier', '压缩工具', 2),
    ('miniprogram', '小程序', 2),
    ('mirror-sites', '镜像站', 1),
    ('mixed-content', 'mixed 内容', 2),
    ('mnemonic', '助记词', 1),
    ('mockup-editor', 'mockup 编辑器', 1),
    ('model-hub', '模型 hub', 2),
    ('module-federation', '模块联邦', 2),
    ('module-formats', '模块格式', 1),
    ('momentjs-alternative', 'momentjs 替代方案', 1),
    ('motion-graphics', '动效图形', 1),
    ('mouse-events', '鼠标事件', 1),
    ('multi-line-ellipsis', '多行省略', 1),
    ('multichain', '多链', 13),
    ('multiple-formats', '多格式', 1),
    ('naiveui', 'naive-ui', 3),
    ('naming-conventions', '命名约定', 1),
    ('national-geographic', '国家地理', 1),
    ('nested-conditions', '嵌套条件', 1),
    ('netflix-conductor', 'netflix conductor', 1),
    ('network-tools', '网络工具', 1),
    ('network-wide', '全局网络', 1),
    ('neural-network', '神经网络', 1),
    ('new-tokens', '新代币', 1),
    ('nextauth', 'next-auth', 2),
    ('ngmodel', 'ng-model', 2),
    ('no-ads', '无广告', 1),
    ('nodejs-framework', 'nodejs 框架', 1),
    ('notion-alternative', 'notion 替代方案', 1),
    ('novel', '小说', 1),
    ('number-manipulation', '数字操作', 1),
    ('numerical-computing', '数值计算', 1),
    ('nvchad', '英伟达', 1),
    ('obfuscation', '混淆', 3),
    ('object-removal', '对象移除', 2),
    ('official', '官方', 1),
    ('official-wrapper', '官方封装', 1),
    ('oh-my-zsh', 'oh my zsh', 1),
    ('omni-route', 'omni-rote', 1),
    ('on-device-ai', '端侧 AI', 1),
    ('onchain', '链上', 3),
    ('onchain-analytics', '链上分析', 1),
    ('online-playground', '在线playground', 1),
    ('open-source-badges', '开放源码徽章', 1),
    ('options-request', 'options请求', 1),
    ('orchestration', '编排', 2),
    ('os-detection', 'os 检测', 1),
    ('package-explorer', '包浏览器', 1),
    ('package-manager', '包管理器', 6),
    ('package-size', '包体积', 1),
    ('page-lifecycle', '页面生命周期', 1),
    ('page-size', '页面尺寸', 2),
    ('page-transition', '页面过渡', 1),
    ('paged-media', 'PageSize', 2),
    ('parallel-agents', '多 agent 并行', 1),
    ('password-mask', '密码mask', 1),
    ('passwordless', '无密码登录', 1),
    ('pattern-matching', '模式匹配', 1),
    ('pen-tool', '钢笔工具', 1),
    ('persistent-vectors', '持久化向量', 1),
    ('personal-blog', '个人博客', 1),
    ('personal-site', '个人网站', 1),
    ('pinyin', '拼音', 1),
    ('pixi-js', 'pixi JS', 1),
    ('plugin-collection', '插件合集', 1),
    ('plugin-manager', '插件管理器', 1),
    ('podcast', '播客', 1),
    ('port-forwarding', '端口转发', 1),
    ('port-scanning', '端口扫描', 3),
    ('postman-alternative', 'postman 替代方案', 2),
    ('ppt-generation', 'PPT 生成', 2),
    ('pre-commit', '提交前检查', 1),
    ('pre-tge', 'pre tge', 1),
    ('print-styles', '打印样式', 1),
    ('product-tour', '产品导览', 1),
    ('programmer-resources', '程序员资源', 1),
    ('programming-ebooks', '编程电子书', 1),
    ('programming-languages', '编程语言', 1),
    ('progress-bar', '进度条', 1),
    ('progressive-enhancement', '渐进式增强', 1),
    ('project-information', '项目信息', 1),
    ('prop-types', 'PropTypes', 1),
    ('public-apis', '公共 API', 1),
    ('publish-size', '发布体积', 1),
    ('publish-subscribe', '发布订阅', 2),
    ('pull-to-refresh', '下拉刷新', 1),
    ('pump-fun', 'pump fun', 1),
    ('qq-show', 'QQ 秀', 1),
    ('qr-code-decoder', '二维码解码器', 1),
    ('quantitative-trading', '量化交易', 1),
    ('query', '查询', 3),
    ('query-builder', '查询构建器', 3),
    ('query-language', '查询语言', 1),
    ('quests', '任务', 1),
    ('quick-reference', '快速参考', 2),
    ('reactive', '响应式', 4),
    ('reactive-streams', '响应式流', 1),
    ('readme', 'README', 2),
    ('realtime-info', '实时信息', 1),
    ('receive-sms-online', '在线接收短信', 1),
    ('recharge', '充值', 1),
    ('remote-functions', '远程函数', 1),
    ('reproducible-builds', '可复现构建', 1),
    ('resolution-enhancement', '分辨率增强', 1),
    ('resource-collection', '资源合集', 5),
    ('risk-mitigation', '风险缓解', 1),
    ('route-reuse-strategy', '路由复用策略', 1),
    ('rug-pull', '项目跑路', 1),
    ('running-elements', '运行元素', 1),
    ('runtime-types', '运行时类型', 3),
    ('script-repository', '脚本仓库', 1),
    ('scroll-snap', '滚动吸附', 2),
    ('scroll-to-error', '滚动到错误处', 2),
    ('scrollbar', '滚动条', 4),
    ('seam-carving', '接缝裁剪', 1),
    ('search-and-replace', '搜索替换', 2),
    ('security-tools', '安全工具', 1),
    ('seed-phrase', '助记词', 1),
    ('semantic-retrieval', '语义检索', 1),
    ('sentry-compatible', 'sentry 兼容', 1),
    ('shadow', '阴影', 1),
    ('show-more', '展开更多', 1),
    ('silent-login', '静默登录', 1),
    ('sms', '短信', 5),
    ('software-complexity', '软件复杂度', 1),
    ('sortable', '排序', 5),
    ('sortable-table', '排序表格', 1),
    ('speech-synthesis', '语音合成', 1),
    ('splash-screen', '启动图', 1),
    ('split-view', '分栏视图', 1),
    ('stable-diffusion', 'Stable Diffusion', 6),
    ('stacking-context', '层叠上下文', 2),
    ('starter-kit', '启动套件', 3),
    ('startpage', '落地页', 1),
    ('static-site-generator', '静态网站生成器', 2),
    ('stealth-browser', '隐身浏览器', 1),
    ('sticky-columns', '吸附列', 5),
    ('sticky-notes', '便利贴', 1),
    ('stock-photos', '照片图库', 5),
    ('stroke-animation', '描边动画', 1),
    ('strong-typing', '强类型', 1),
    ('structural-patterns', '结构型模式', 1),
    ('study-abroad', '留学', 1),
    ('supply-chain-security', '供应链安全', 1),
    ('symmetry', '对称', 1),
    ('synapse-protocol', 'synapse 协议', 1),
    ('tail-call-optimization', '尾调用优化', 1),
    ('tainted-canvas', '污染 Canvas', 2),
    ('task-automation', '任务自动化', 1),
    ('task-runner', '任务运行器', 2),
    ('tech-blog', '技术博客', 1),
    ('technology-profiler', '技术分析器', 1),
    ('technology-stack', '技术栈', 2),
    ('television', '电视', 1),
    ('temporal-memory', '时序记忆', 1),
    ('temporary-phone-number', '临时电话', 4),
    ('test-runner', '测试运行器', 1),
    ('text-animation', '文本动画', 2),
    ('text-effects', '文本效果', 3),
    ('text-selection', '文本选择', 1),
    ('text-to-image', '文生图', 1),
    ('text-to-video', '文生视频', 2),
    ('text-wrap', '文本换行', 1),
    ('texturing', '纹理', 1),
    ('theme-switching', '主题切换', 2),
    ('third-party-scripts', '第三方脚本', 1),
    ('thread-pool', '线程池', 2),
    ('tidb-cloud', 'tidb 云', 1),
    ('timepicker', '时间选择器', 1),
    ('toggle-switch', '开关切换', 2),
    ('token-approvals', 'token 审批', 2),
    ('token-creator', 'token 创建工具', 1),
    ('token-explorer', 'token 浏览器', 1),
    ('token-launchpad', '代币发行平台', 1),
    ('token-sale', 'token 销售', 1),
    ('token-vesting', 'token 解锁', 1),
    ('tool-collection', '工具合集', 3),
    ('tool-use', '工具使用', 1),
    ('tornado-cash', 'tornado cash', 1),
    ('traditional-colors', '传统颜色', 1),
    ('transaction-tracer', '交易追踪器', 1),
    ('transpiler', '转译器', 3),
    ('tv-shows', '电视节目', 1),
    ('two-way-binding', '双向绑定', 1),
    ('type-definitions', '类型定义', 1),
    ('type-library', '类型库', 1),
    ('type-system', '类型系统', 1),
    ('typesafe', '类型安全', 1),
    ('typing-animation', '打字动画', 1),
    ('unused-dependencies', '未使用依赖', 2),
    ('unused-files', '未使用文件', 2),
    ('url-friendly', 'URL 友好', 1),
    ('url-shortener', 'URL 短链工具', 4),
    ('us-proxy', '美国代理', 1),
    ('use-event-listener', '使用事件监听器', 1),
    ('usehooks-ts', 'usehooks ts', 2),
    ('userscript', '用户脚本', 2),
    ('utility-classes', '实用工具类', 1),
    ('utility-first', '实用工具优先', 3),
    ('utility-types', '实用类型', 2),
    ('velocity-js', 'velocity JS', 1),
    ('version-manager', '版本管理器', 1),
    ('video-downloader', '视频下载器', 2),
    ('video-generation', '视频生成', 3),
    ('video-processing', '视频处理', 2),
    ('viewport-units', '视口单位', 1),
    ('virtual-phone-number', '虚拟电话', 5),
    ('virtual-tour', '虚拟导览', 2),
    ('virtualized-table', '虚拟化表格', 1),
    ('visual-effects', '可视化效果', 1),
    ('visual-feedback', '可视化反馈', 1),
    ('visual-mode', '可视模式', 1),
    ('web-based', 'Web 应用', 2),
    ('web-dev', 'Web 开发', 2),
    ('web-ssh', 'Web SSH', 1),
    ('web-standards', 'Web 标准', 2),
    ('web-to-desktop', 'Web 转桌面端', 1),
    ('web-vitals', 'Web 核心指标', 2),
    ('web-workers', 'Web-workers', 3),
    ('window-opener', '窗口打开器', 1),
    ('wired-elements', '手绘风格', 1),
    ('wireframing', '线框设计', 1),
    ('word-roots', '词根', 1),
    ('worker-threads', '工作线程', 1),
    ('yield-farming', '流动性挖矿', 1),
    ('yield-layer', '收益层', 1);

CREATE TEMP TABLE migration_assert (
    value INTEGER NOT NULL CHECK (value = 1)
);

INSERT INTO migration_assert
SELECT count(*) = 550
FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

INSERT INTO migration_assert
SELECT count(*) = 0
FROM tag_localization_map mapping
WHERE mapping.expected_count != (
    SELECT count(*)
    FROM bookmark_tags bt
    JOIN tags source ON source.id = bt.tag_id
    WHERE source.name = mapping.source
);

INSERT INTO migration_assert
SELECT count(*) = 0
FROM tag_localization_map
WHERE source = target OR target != trim(target) OR target = '' OR instr(target, ',') > 0;

INSERT OR IGNORE INTO tags(name)
SELECT DISTINCT target FROM tag_localization_map;

INSERT INTO bookmark_tags(bookmark_id, tag_id)
SELECT bt.bookmark_id, target.id
FROM tag_localization_map mapping
JOIN tags source ON source.name = mapping.source
JOIN bookmark_tags bt ON bt.tag_id = source.id
JOIN tags target ON target.name = mapping.target
ON CONFLICT(bookmark_id, tag_id) DO NOTHING;

DELETE FROM bookmark_tags
WHERE tag_id IN (
    SELECT id FROM tags WHERE name IN (SELECT source FROM tag_localization_map)
);

DELETE FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

DELETE FROM bookmarks_fts;
INSERT INTO bookmarks_fts(rowid, url, title, description, tags)
SELECT b.id, b.url, b.title, b.description,
       coalesce((
           SELECT group_concat(name, ' ')
           FROM (
               SELECT t.name AS name
               FROM bookmark_tags bt
               JOIN tags t ON t.id = bt.tag_id
               WHERE bt.bookmark_id = b.id
               ORDER BY t.name
           )
       ), '')
FROM bookmarks b;

INSERT INTO migration_assert SELECT count(*) = 2163 FROM bookmarks;
INSERT INTO migration_assert SELECT count(*) = 2159 FROM tags;
INSERT INTO migration_assert SELECT count(*) = 10426 FROM bookmark_tags;
INSERT INTO migration_assert
SELECT count(*) = 0
FROM bookmarks b
WHERE NOT EXISTS (
    SELECT 1 FROM bookmark_tags bt WHERE bt.bookmark_id = b.id
);
INSERT INTO migration_assert
SELECT count(*) = 0
FROM tags t
WHERE NOT EXISTS (
    SELECT 1 FROM bookmark_tags bt WHERE bt.tag_id = t.id
);
INSERT INTO migration_assert SELECT count(*) = 0 FROM pragma_foreign_key_check;
INSERT INTO migration_assert SELECT count(*) = 2163 FROM bookmarks_fts;
INSERT INTO migration_assert
SELECT count(*) = 0
FROM tags
WHERE name IN (SELECT source FROM tag_localization_map);

COMMIT;
