// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getCalendarDays: (request: CalendarRangeRequest) => typedError<CalendarDay[], AppError>(__TAURI_INVOKE("get_calendar_days", { request })),
	listCalendarEvents: (startDate: string, endDate: string) => typedError<CalendarEvent[], AppError>(__TAURI_INVOKE("list_calendar_events", { startDate, endDate })),
	createCalendarEvent: (input: CreateCalendarEvent) => typedError<CalendarEvent, AppError>(__TAURI_INVOKE("create_calendar_event", { input })),
	updateCalendarEvent: (id: CalendarEventId, input: UpdateCalendarEvent) => typedError<CalendarEvent, AppError>(__TAURI_INVOKE("update_calendar_event", { id, input })),
	deleteCalendarEvent: (id: CalendarEventId) => typedError<null, AppError>(__TAURI_INVOKE("delete_calendar_event", { id })),
	listNavigationSections: () => typedError<NavigationSection[], AppError>(__TAURI_INVOKE("list_navigation_sections")),
	createNavigationCategory: (input: CreateNavigationCategory) => typedError<NavigationCategory, AppError>(__TAURI_INVOKE("create_navigation_category", { input })),
	updateNavigationCategory: (id: NavigationCategoryId, input: UpdateNavigationCategory) => typedError<NavigationCategory, AppError>(__TAURI_INVOKE("update_navigation_category", { id, input })),
	deleteNavigationCategory: (id: NavigationCategoryId) => typedError<null, AppError>(__TAURI_INVOKE("delete_navigation_category", { id })),
	reorderNavigationCategories: (input: ReorderNavigationCategories) => typedError<null, AppError>(__TAURI_INVOKE("reorder_navigation_categories", { input })),
	addNavigationBookmarks: (categoryId: NavigationCategoryId, input: AddNavigationBookmarks) => typedError<NavigationPlacementCard[], AppError>(__TAURI_INVOKE("add_navigation_bookmarks", { categoryId, input })),
	removeNavigationBookmark: (categoryId: NavigationCategoryId, bookmarkId: BookmarkId) => typedError<null, AppError>(__TAURI_INVOKE("remove_navigation_bookmark", { categoryId, bookmarkId })),
	queryBookmarks: (request: BookmarkPageRequest) => typedError<BookmarkPage, AppError>(__TAURI_INVOKE("query_bookmarks", { request })),
	createBookmark: (input: CreateBookmark) => typedError<Bookmark, AppError>(__TAURI_INVOKE("create_bookmark", { input })),
	updateBookmark: (id: BookmarkId, input: UpdateBookmark) => typedError<Bookmark, AppError>(__TAURI_INVOKE("update_bookmark", { id, input })),
	deleteBookmarks: (ids: BookmarkId[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_bookmarks", { ids })),
	getBookmarkByUrl: (url: string) => typedError<{
	id: BookmarkId,
	url: string,
	title: string,
	description: string,
	tags: string[],
	access_count: number,
	created_at: string,
	updated_at: string,
	accessed_at: string | null,
	starred_at: string | null,
} | null, AppError>(__TAURI_INVOKE("get_bookmark_by_url", { url })),
	getTags: (request: TagQueryRequest) => typedError<TagSummary[], AppError>(__TAURI_INVOKE("get_tags", { request })),
	recordBookmarkAccess: (id: BookmarkId) => typedError<Bookmark, AppError>(__TAURI_INVOKE("record_bookmark_access", { id })),
	setBookmarkStarred: (id: BookmarkId, starred: boolean) => typedError<Bookmark, AppError>(__TAURI_INVOKE("set_bookmark_starred", { id, starred })),
	prepareBookmarkPreview: (request: PrepareBookmarkPreviewRequest, forceRefresh: boolean) => typedError<BookmarkPreview, AppError>(__TAURI_INVOKE("prepare_bookmark_preview", { request, forceRefresh })),
	previewRssFeed: (url: string) => typedError<FeedPreview, AppError>(__TAURI_INVOKE("preview_rss_feed", { url })),
	createRssFeed: (input: CreateFeed) => typedError<RssFeed, AppError>(__TAURI_INVOKE("create_rss_feed", { input })),
	listRssFeeds: () => typedError<RssFeed[], AppError>(__TAURI_INVOKE("list_rss_feeds")),
	listRssEntries: (request: EntryPageRequest) => typedError<EntryPage, AppError>(__TAURI_INVOKE("list_rss_entries", { request })),
	refreshRssFeed: (id: RssFeedId) => typedError<FeedRefreshResult, AppError>(__TAURI_INVOKE("refresh_rss_feed", { id })),
	refreshAllRssFeeds: (staleOnly: boolean) => typedError<RefreshResult, AppError>(__TAURI_INVOKE("refresh_all_rss_feeds", { staleOnly })),
	markRssEntryRead: (id: RssEntryId, isRead: boolean) => typedError<RssEntry, AppError>(__TAURI_INVOKE("mark_rss_entry_read", { id, isRead })),
	renameRssFeed: (id: RssFeedId, customTitle: string | null) => typedError<RssFeed, AppError>(__TAURI_INVOKE("rename_rss_feed", { id, customTitle })),
	deleteRssFeed: (id: RssFeedId) => typedError<null, AppError>(__TAURI_INVOKE("delete_rss_feed", { id })),
	downloadRssImage: (url: string, referer: string | null, destination: string) => typedError<null, AppError>(__TAURI_INVOKE("download_rss_image", { url, referer, destination })),
	queryTodos: (request: TodoQuery) => typedError<TodoList, AppError>(__TAURI_INVOKE("query_todos", { request })),
	getTodoTags: () => typedError<TodoTag[], AppError>(__TAURI_INVOKE("get_todo_tags")),
	createTodo: (input: CreateTodo) => typedError<Todo, AppError>(__TAURI_INVOKE("create_todo", { input })),
	updateTodo: (id: TodoId, input: UpdateTodo) => typedError<Todo, AppError>(__TAURI_INVOKE("update_todo", { id, input })),
	setTodoStatus: (id: TodoId, status: TodoStatus) => typedError<Todo, AppError>(__TAURI_INVOKE("set_todo_status", { id, status })),
	deleteTodo: (id: TodoId) => typedError<null, AppError>(__TAURI_INVOKE("delete_todo", { id })),
	renameTodoTag: (id: TodoTagId, name: string) => typedError<TodoTag, AppError>(__TAURI_INVOKE("rename_todo_tag", { id, name })),
	deleteTodoTag: (id: TodoTagId) => typedError<null, AppError>(__TAURI_INVOKE("delete_todo_tag", { id })),
	archiveDeleteTodoTag: (id: TodoTagId) => typedError<null, AppError>(__TAURI_INVOKE("archive_delete_todo_tag", { id })),
	exportTodos: (path: string, tagId: string | null) => typedError<string, AppError>(__TAURI_INVOKE("export_todos", { path, tagId })),
	exportBookmarkDataset: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("export_bookmark_dataset", { path })),
	getBookmarkInitializationStatus: () => typedError<BookmarkInitializationStatus, AppError>(__TAURI_INVOKE("get_bookmark_initialization_status")),
	initializeBookmarks: (path: string) => typedError<BookmarkInitializationResult, AppError>(__TAURI_INVOKE("initialize_bookmarks", { path })),
	scanNotes: () => typedError<NotesWorkspaceListing, AppError>(__TAURI_INVOKE("scan_notes")),
	openNoteDocument: (revision: number, relativePath: string) => typedError<OpenedDocument, AppError>(__TAURI_INVOKE("open_note_document", { revision, relativePath })),
	openHtmlDocument: (revision: number, relativePath: string) => typedError<OpenedHtmlDocument, AppError>(__TAURI_INVOKE("open_html_document", { revision, relativePath })),
	openExternalNoteFile: (revision: number, relativePath: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external_note_file", { revision, relativePath })),
	saveNoteDocument: (receipt: string, content: string) => typedError<SavedDocument, AppError>(__TAURI_INVOKE("save_note_document", { receipt, content })),
	renameNoteDocument: (receipt: string, name: string, pendingContent: string | null) => typedError<RenamedDocument, AppError>(__TAURI_INVOKE("rename_note_document", { receipt, name, pendingContent })),
	deleteNoteDocument: (receipt: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note_document", { receipt })),
	renameWorkspaceFile: (revision: number, relativePath: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_workspace_file", { revision, relativePath, name })),
	deleteWorkspaceFile: (revision: number, relativePath: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_workspace_file", { revision, relativePath })),
	createNoteFile: (revision: number, directory: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("create_note_file", { revision, directory, name })),
	preflightNoteFolderDeletion: (revision: number, relativePath: string) => typedError<FolderDeletionSummary, AppError>(__TAURI_INVOKE("preflight_note_folder_deletion", { revision, relativePath })),
	deleteNoteFolder: (receipt: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note_folder", { receipt })),
	getSettings: () => typedError<SettingsSnapshot, AppError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (expectedRevision: number, settings: Settings) => typedError<SettingsSnapshot, AppError>(__TAURI_INVOKE("update_settings", { expectedRevision, settings })),
	activateProvider: (expectedRevision: number, capability: Capability, providerId: ProviderId) => typedError<SettingsSnapshot, AppError>(__TAURI_INVOKE("activate_provider", { expectedRevision, capability, providerId })),
	deactivateProvider: (expectedRevision: number, capability: Capability) => typedError<SettingsSnapshot, AppError>(__TAURI_INVOKE("deactivate_provider", { expectedRevision, capability })),
	getServerStatus: () => typedError<ServerStatus_Serialize, AppError>(__TAURI_INVOKE("get_server_status")),
	getSystemInfo: () => typedError<SystemInfo, AppError>(__TAURI_INVOKE("get_system_info")),
};

/* Types */
export type AddNavigationBookmarks = {
	bookmark_ids: BookmarkId[],
};

export type AppError = {
	code: string,
	message: string,
};

export type Bookmark = {
	id: BookmarkId,
	url: string,
	title: string,
	description: string,
	tags: string[],
	access_count: number,
	created_at: string,
	updated_at: string,
	accessed_at: string | null,
	starred_at: string | null,
};

export type BookmarkId = string;

export type BookmarkInitializationResult = {
	bookmark_count: number,
	navigation_category_count: number,
};

export type BookmarkInitializationStatus = {
	can_initialize: boolean,
};

export type BookmarkPage = {
	items: Bookmark[],
	next_cursor: string | null,
};

export type BookmarkPageRequest = { mode: "browse"; starred?: boolean; cursor: string | null; page_size: number } | { mode: "search"; query?: string; tags?: string[]; cursor: string | null; page_size: number } | { mode: "random"; limit: number };

export type BookmarkPreview = { kind: "web"; url: string; final_url: string } | { kind: "github_repository"; url: string; repository: GithubRepositoryPreview } | { kind: "fallback"; url: string; reason: PreviewFallbackReason; message: string; http_status: number | null };

export type CalendarDay = {
	date: string,
	lunar_date: LunarDateSummary | null,
	solar_term: string | null,
	holidays: HolidayAnnotation[],
	events: CalendarEventSummary[],
	todos: CalendarTodoSummary[],
};

export type CalendarEvent = {
	id: CalendarEventId,
	title: string,
	date: string,
	event_type: CalendarEventType,
	created_at: string,
	updated_at: string,
};

export type CalendarEventId = string;

export type CalendarEventSummary = {
	id: string,
	title: string,
	event_type: CalendarEventType,
	source: string,
};

export type CalendarEventType = "work" | "personal" | "anniversary" | "other";

export type CalendarHolidayDayType = "day_off" | "adjusted_workday" | "observance";

export type CalendarRangeRequest = {
	start_date: string,
	end_date: string,
};

export type CalendarTodoDateType = "start" | "due";

export type CalendarTodoSummary = {
	id: string,
	title: string,
	date_type: CalendarTodoDateType,
};

export type Capability = "translation" | "ai";

export type CapabilitySettings = {
	translation?: ProviderRouteSettings,
};

export type CommonSettings = {
	paths?: PathSettings,
};

export type CreateBookmark = {
	url: string,
	title: string,
	description: string,
	tags: string[],
};

export type CreateCalendarEvent = {
	title: string,
	date: string,
	event_type?: CalendarEventType,
};

export type CreateFeed = {
	source_url: string,
	feed_url: string,
	custom_title: string | null,
};

export type CreateNavigationCategory = {
	name: string,
};

export type CreateTodo = {
	title: string,
	description?: string,
	is_high_priority?: boolean,
	tags?: string[],
	start_date?: string | null,
	due_date?: string | null,
};

export type EntryPage = {
	entries: RssEntry[],
	next_cursor: string | null,
};

export type EntryPageRequest = {
	scope: EntryQueryScope,
	cursor: string | null,
};

export type EntryQueryScope = { mode: "all" } | { mode: "unread" } | { mode: "feed"; feed_id: RssFeedId };

export type FeedCandidate = {
	title: string | null,
	feed_url: string,
	site_url: string | null,
	recent_entries: FeedPreviewEntry[],
};

export type FeedPreview = {
	source_url: string,
	candidates: FeedCandidate[],
};

export type FeedPreviewEntry = {
	title: string,
	published_at: number | null,
};

export type FeedRefreshResult = {
	feed: RssFeed,
	added: number,
};

export type FolderDeletionSummary = {
	file_count: number,
	directory_count: number,
	invisible_entry_count: number,
	receipt: string,
};

export type GithubRepositoryPreview = {
	owner: string,
	name: string,
	full_name: string,
	description: string | null,
	html_url: string,
	owner_avatar_url: string | null,
	primary_language: string | null,
	stars: number,
	forks: number,
	topics: string[],
	default_branch: string,
	updated_at: string,
};

export type HolidayAnnotation = {
	name: string,
	display_name: string,
	day_type: CalendarHolidayDayType,
	source: string,
};

export type HttpServerPhase = "running" | "failed" | "stopping" | "stopped";

export type LunarDateSummary = {
	year: number,
	month: number,
	day: number,
	is_leap_month: boolean,
	month_name: string,
	day_name: string,
};

export type NavigationCategory = {
	id: NavigationCategoryId,
	name: string,
	order: number,
	created_at: number,
	updated_at: number,
};

export type NavigationCategoryId = string;

export type NavigationPlacementCard = {
	placement_id: NavigationPlacementId,
	bookmark_id: BookmarkId,
	title: string,
	url: string,
	created_at: number,
};

export type NavigationPlacementId = string;

export type NavigationSection = {
	category: NavigationCategory,
	cards: NavigationPlacementCard[],
};

export type NiuTransSettings = {
	app_id?: string | null,
	api_key?: string | null,
};

export type NotesWorkspaceListing = {
	revision: number,
	root: WorkspaceDirectory,
};

export type OpenedDocument = {
	content: string,
	receipt: string,
};

export type OpenedHtmlDocument = {
	content: string,
};

export type PathSettings = {
	bookmark_export_dir?: string | null,
	todo_export_dir?: string | null,
	notes_dir?: string | null,
};

export type PrepareBookmarkPreviewRequest = {
	bookmark_id: BookmarkId,
	url: string,
};

export type PreviewFallbackReason = "embedding_denied" | "timeout" | "dns_failure" | "connection_failure" | "http_error" | "unsupported_protocol" | "unsupported_provider_url" | "provider_rate_limited" | "provider_not_found" | "provider_error" | "unsafe_target";

export type ProviderActivation = "inactive" | "primary" | { fallback: {
	position: number,
} };

export type ProviderDescriptor = {
	id: ProviderId,
	capability: Capability,
	display_name: string,
	description: string,
};

export type ProviderId = string;

export type ProviderRouteSettings = {
	primary_provider?: ProviderId | null,
	fallback_providers?: ProviderId[],
};

export type ProviderSettings = {
	niutrans?: NiuTransSettings,
};

export type ProviderStatusView = {
	descriptor: ProviderDescriptor,
	configured: boolean,
	activation: ProviderActivation,
};

export type RefreshResult = {
	refreshed: number,
	added: number,
	failed: number,
};

export type RenamedDocument = {
	relative_path: string,
	receipt: string,
};

export type ReorderNavigationCategories = {
	category_ids: NavigationCategoryId[],
};

export type RssEntry = {
	id: RssEntryId,
	feed_id: RssFeedId,
	feed_title: string,
	title: string,
	link: string | null,
	author: string | null,
	content_html: string,
	summary: string,
	published_at: number | null,
	fetched_at: number,
	is_read: boolean,
};

export type RssEntryId = string;

export type RssFeed = {
	id: RssFeedId,
	source_url: string,
	feed_url: string,
	site_url: string | null,
	title: string,
	custom_title: string | null,
	entry_count: number,
	unread_count: number,
	last_successful_fetched_at: number | null,
	last_failed_at: number | null,
	last_error: string | null,
	created_at: number,
	updated_at: number,
};

export type RssFeedId = string;

export type RssHubSettings = {
	base_url?: string | null,
	access_key?: string | null,
};

export type SavedDocument = {
	receipt: string,
};

export type ServerStatus = ServerStatus_Serialize | ServerStatus_Deserialize;

export type ServerStatus_Deserialize = {
	running: boolean,
	url: string,
	phase: HttpServerPhase,
	error_code: string | null,
};

export type ServerStatus_Serialize = {
	running: boolean,
	url: string,
	phase: HttpServerPhase,
	error_code?: string | null,
};

export type ServiceSettings = {
	rsshub?: RssHubSettings,
};

export type Settings = {
	schema_version?: number,
	common?: CommonSettings,
	capabilities?: CapabilitySettings,
	providers?: ProviderSettings,
	services?: ServiceSettings,
};

export type SettingsSnapshot = {
	revision: number,
	settings: Settings,
	providers: ProviderStatusView[],
};

export type SystemInfo = {
	app_data_dir: string,
	sqlite_db_path: string,
	schema_version: number,
	search_backend: string,
	app_version: string,
};

export type TagQueryRequest = {
	query?: string,
	limit: number | null,
};

export type TagSummary = {
	name: string,
	count: number,
};

export type Todo = {
	id: TodoId,
	title: string,
	description: string,
	status: TodoStatus,
	is_high_priority: boolean,
	tags: string[],
	start_date: string | null,
	due_date: string | null,
	created_at: string,
	updated_at: string,
	completed_at: string | null,
};

export type TodoId = string;

export type TodoList = {
	items: Todo[],
	total: number,
	completed: number,
};

export type TodoQuery = {
	status: TodoStatus | null,
	tag_id: TodoTagId | null,
};

export type TodoStatus = "in_progress" | "completed" | "suspended" | "canceled";

export type TodoTag = {
	id: TodoTagId,
	name: string,
	count: number,
};

export type TodoTagId = string;

export type UpdateBookmark = {
	url: string | null,
	title: string | null,
	description: string | null,
	tags: string[] | null,
};

export type UpdateCalendarEvent = {
	title: string,
	date: string,
	event_type: CalendarEventType,
};

export type UpdateNavigationCategory = {
	name: string,
};

export type UpdateTodo = {
	title: string,
	description: string,
	is_high_priority: boolean,
	tags: string[],
	start_date: string | null,
	due_date: string | null,
};

export type WorkspaceDirectory = {
	name: string,
	relative_path: string,
	directories: WorkspaceDirectory[],
	files: WorkspaceFile[],
};

export type WorkspaceFile = {
	name: string,
	relative_path: string,
	kind: WorkspaceFileKind,
	capabilities: WorkspaceFileCapabilities,
};

export type WorkspaceFileCapabilities = {
	primary_interaction: WorkspaceFilePrimaryInteraction,
	can_rename: boolean,
	can_delete: boolean,
	can_open_with_system: boolean,
};

export type WorkspaceFileKind = "markdown" | "html" | "external";

export type WorkspaceFilePrimaryInteraction = "edit" | "view" | "system_open" | "unavailable";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

